#include "dbg.hpp"

std::vector<std::string> eventNames = {
	{"DN_FIRST"},
	{"DN_BTNCLICK"},
	{"DN_CTLCOLORDIALOG"},
	{"DN_CTLCOLORDLGITEM"},
	{"DN_CTLCOLORDLGLIST"},
	{"DN_DRAWDIALOG"},
	{"DN_DRAWDLGITEM"},
	{"DN_EDITCHANGE"},
	{"DN_ENTERIDLE"},
	{"DN_GOTFOCUS"},
	{"DN_HELP"},
	{"DN_HOTKEY"},
	{"DN_INITDIALOG"},
	{"DN_KILLFOCUS"},
	{"DN_LISTCHANGE"},
	{"DN_MOUSECLICK"},
	{"DN_DRAGGED"},
	{"DN_RESIZECONSOLE"},
	{"DN_MOUSEEVENT"},
	{"DN_DRAWDIALOGDONE"},
};

std::vector<std::string> messageNames = {
	{"DM_FIRST=0,"},
	{"DM_CLOSE,"},
	{"DM_ENABLE,"},
	{"DM_ENABLEREDRAW,"},
	{"DM_GETDLGDATA,"},
	{"DM_GETDLGITEM,"},
	{"DM_GETDLGRECT,"},
	{"DM_GETTEXT,"},
	{"DM_GETTEXTLENGTH,"},
	{"DM_KEY,"},
	{"DM_MOVEDIALOG,"},
	{"DM_SETDLGDATA,"},
	{"DM_SETDLGITEM,"},
	{"DM_SETFOCUS,"},
	{"DM_REDRAW,"},
	{"DM_SETREDRAW=DM_REDRAW,"},
	{"DM_SETTEXT,"},
	{"DM_SETMAXTEXTLENGTH,"},
	{"DM_SETTEXTLENGTH=DM_SETMAXTEXTLENGTH,"},
	{"DM_SHOWDIALOG,"},
	{"DM_GETFOCUS,"},
	{"DM_GETCURSORPOS,"},
	{"DM_SETCURSORPOS,"},
	{"DM_GETTEXTPTR,"},
	{"DM_SETTEXTPTR,"},
	{"DM_SHOWITEM,"},
	{"DM_ADDHISTORY,"},

	{"DM_GETCHECK,"},
	{"DM_SETCHECK,"},
	{"DM_SET3STATE,"},

	{"DM_LISTSORT,"},
	{"DM_LISTGETITEM,"},
	{"DM_LISTGETCURPOS,"},
	{"DM_LISTSETCURPOS,"},
	{"DM_LISTDELETE,"},
	{"DM_LISTADD,"},
	{"DM_LISTADDSTR,"},
	{"DM_LISTUPDATE,"},
	{"DM_LISTINSERT,"},
	{"DM_LISTFINDSTRING,"},
	{"DM_LISTINFO,"},
	{"DM_LISTGETDATA,"},
	{"DM_LISTSETDATA,"},
	{"DM_LISTSETTITLES,"},
	{"DM_LISTGETTITLES,"},

	{"DM_RESIZEDIALOG,"},
	{"DM_SETITEMPOSITION,"},

	{"DM_GETDROPDOWNOPENED,"},
	{"DM_SETDROPDOWNOPENED,"},

	{"DM_SETHISTORY,"},

	{"DM_GETITEMPOSITION,"},
	{"DM_SETMOUSEEVENTNOTIFY,"},

	{"DM_EDITUNCHANGEDFLAG,"},

	{"DM_GETITEMDATA,"},
	{"DM_SETITEMDATA,"},

	{"DM_LISTSET,"},
	{"DM_LISTSETMOUSEREACTION,"},

	{"DM_GETCURSORSIZE,"},
	{"DM_SETCURSORSIZE,"},

	{"DM_LISTGETDATASIZE,"},

	{"DM_GETSELECTION,"},
	{"DM_SETSELECTION,"},

	{"DN_LISTHOTKEY,"},

	{"DM_GETEDITPOSITION,"},
	{"DM_SETEDITPOSITION,"},

	{"DM_SETCOMBOBOXEVENT,"},
	{"DM_GETCOMBOBOXEVENT,"},
};


std::string GetMessageName(int msg)
{
	if (msg > DN_FIRST)
	{
		return eventNames[msg - DN_FIRST];
	}
	else
	{
		return messageNames[msg];
	}
}